### ISSUE TITLE
Overlapping issues - looking for paid expert to solve the issues

### ISSUE THREAD

**Issue by simplenotezy** [ducksboard/gridster.js#327]
Hello there!

We are having issues with our grids - when elements become too large they overlap each other - not always, but often.

We would like to hear from anybody, who could find it interesting to look into to the problem, and solve the issue, if he have found the source of the problem. We will, of course pay.

Please let me know.

**Comment by skozz** [comment]
What version are you using? I fixed it updating to 0.5

**Comment by bedomon** [comment]
With last version there is still problem with overlap espacially with the css position attribute...

**Comment by simplenotezy** [comment]
Wow - they have been developing a lot on gridster. Good to see (i was at version 0.2). But unfortunately, the issue still presists.

**Comment by simplenotezy** [comment]
I have gotten a little closer to the problem. See: https://github.com/ducksboard/gridster.js/issues/340
