### ISSUE TITLE
Resizing bug on bottom displayed grid elements

### ISSUE THREAD

**Issue by hoyer-io** [ducksboard/gridster.js#53]
When an element in the grid is resized by height and it lies in the last row of the grid, the outer grid size is not updated, so the resized element overlaps the outer grid. When you drag it afterwards the outer grid is resized, too.

**Comment by Kaherdin** [comment]
I've the same problem. If you can fix it, it would be so great.

**Comment by goldnead** [comment]
+1

**Comment by AndyAyrey** [comment]
Further to this:

If there is only a single widget in the bottom row of a grid, resizing it will cause the outer element to collapse, as if the item was removed from the flow of the page.

**Comment by Kaherdin** [comment]
Hello, I fix it.

Find this function : (approx line 885)

/**
    \* Change the size of a widget.
*/

and add
 "this.set_dom_grid_height();" (approx line 1014)

just before 
"return $widget;"

**Comment by hoyer-io** [comment]
So will this be fixed in the official script soon? Otherwise I will go with the bugfix...

**Comment by sinisavukovic** [comment]
@Kaherdin this did the trick, thank you :)

**Comment by ronnyek** [comment]
As best as I can tell with the latest version of gridster from source, this issue still exists and @Kaherdin 's fix doesnt fix it. Resizing the last row doesnt actually resize larger under MOST conditions.

**Comment by lucand** [comment]
Is there any new solution for this problem, or fix from devs?
